version: "3.8"

volumes:
  # Service's data storage volume
  shrekd-data:


services:
  shrekd:
    image: shrekd/shrekd:0.1
    environment:
      SHREKD_ADDRESS: "0.0.0.0"
      SHREKD_PORT: "8000" # Beware, edit the ports section of the service too
      SHREKD_REDIS_URL: "redis://redis:6379"
      SHREKD_DATA_DIR: "/data" # Beware, edit the volumes section of the service too
      SHREKD_SLUG_LENGTH: 13
      SHREKD_MAX_FILE_SIZE: 128000000 # 128 MB
      SHREKD_MAX_PASTE_SIZE: 1000000 # 1 MB
      SHREKD_MAX_URL_SIZE: 32000 # 32 kB
      SHREKD_RETENTION_MIN_AGE: 604800 # 1 week
      SHREKD_RETENTION_MAX_AGE: 1814400 # 3 weeks
    volumes:
      - "shrekd-data:/data"
    ports:
      - "0.0.0.0:8000:8000"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:6.2.3
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped
